baseURL = "https://heathershakespeare.com/"
languageCode = "en-uk"
title = "Heather Shakespeare"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -10
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = -9
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = -8
  [[menu.main]]
    identifier = "poems"
    name = "Poems"
    url = "/poems/"
    weight = -7
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -6
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -5
